[package]
name = "terminome"
version = "0.1.0"
authors = ["veryjos <jos@veryjos.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
tokio = "0.2.0-alpha.2"
term_size = "0.3.1"
humantime = "1.2.0"
